apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hello-cluster
  region: us-east-1

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        imageBuilder: true  

addons:
  fsx: 
    id: fsx-addon

customIAMInstanceProfile:
  name: EKSWorkerNodeProfile

# Define the worker node role and attach policies
iam:
  serviceRoleARN: arn:aws:iam::904982211203:role/EKSClusterRole  

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: Project5   
    iam:
      instanceRoleARN: arn:aws:iam::904982211203:role/EKSWorkerNodeRole  