apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hello-cluster
  region: us-east-1

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::904982211203:role/EKSClusterRole

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        imageBuilder: true

addons:
  fsx: 
    id: fsx-addon

customIAMInstanceProfile:
  name: EKSWorkerNodeProfile